# Generated by rust2rpm-9-1.fc31
%bcond_with check
%global debug_package %{nil}

%global crate ron

Name:           rust-%{crate}
Version:        0.5.1
Release:        4%{?dist}
Summary:        Rusty Object Notation

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/ron
Source:         %{crates_source}
# Initial patched metadata
# * Update serde_bytes to 0.11, https://github.com/ron-rs/ron/pull/164
Patch0:         ron-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(base64/default) >= 0.10.0 with crate(base64/default) < 0.11.0)
BuildRequires:  (crate(bitflags/default) >= 1.0.0 with crate(bitflags/default) < 2.0.0)
BuildRequires:  (crate(serde/default) >= 1.0.0 with crate(serde/default) < 2.0.0)
BuildRequires:  (crate(serde/serde_derive) >= 1.0.0 with crate(serde/serde_derive) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(serde_bytes/default) >= 0.11.0 with crate(serde_bytes/default) < 0.12.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.0 with crate(serde_json/default) < 2.0.0)
%endif

%global _description \
RON is a simple readable data serialization format that looks similar to Rust\
syntax. It's designed to support all of Serde's data model, so structs, enums,\
tuples, arrays, generic maps, and primitive values.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun May 12 08:30:37 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.1-2
- Update serde_bytes to 0.11

* Sat Apr 27 23:09:55 EEST 2019 Artem Polishchuk <ego.cordatus@gmail.com> - 0.5.1-1
- Initial package
